# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    #weather-api nuget updates
  - package-ecosystem: "nuget"
    directory: "services/weather/Weather.Api/"
    schedule:
      interval: "daily"

    #weather-tests nuget updates
  - package-ecosystem: "nuget"
    directory: "services/weather/Weather.Tests/"
    schedule:
      interval: "daily"

    #eucre-game-api nuget updates
  - package-ecosystem: "nuget"
    directory: "services/eucre-game/Games.Eucre.Api/"
    schedule:
      interval: "daily"

    #eucre-game-tests nuget updates
  - package-ecosystem: "nuget"
    directory: "services/eucre-game/Games.Eucre.Tests/"
    schedule:
      interval: "daily"

    #client-app npm updates
  - package-ecosystem: "npm"
    directory: "client/app/"
    schedule:
      interval: "daily"
