version: "3.7"

services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5080:80

  client-tests:
    container_name: client-tests
    build:
      context: ./client/app
      dockerfile: Dockerfile.test

  weather-service:
    container_name: weather-service
    build:
      context: ./services
      dockerfile: weather/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 6010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - storage

  eucre-game:
    container_name: eucre-game
    build:
      context: ./services
      dockerfile: eucre-game/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 6020:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - storage

  library-service:
    container_name: library-service
    build:
      context: ./services
      dockerfile: library/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 6030:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - storage

  lobby-service:
    container_name: lobby-service
    build:
      context: ./services
      dockerfile: lobby/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 6040:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - storage

  profile-service:
    container_name: profile-service
    build:
      context: ./services
      dockerfile: profile/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 6050:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - storage

  mongodb:
    image: mongo:4.2.10
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - storage

  mongodb-client:
    image: mongoclient/mongoclient:4.0.0
    container_name: mongodb-client
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    networks:
      - storage

volumes:
  mongodb:

networks:
  storage:
    driver: bridge
