version: '3.7'

services:
  client-app:
    container_name: client-app
    build:
      context: ./client/app
      dockerfile: Dockerfile
    ports:
      - 5080:80

  client-tests:
    container_name: client-tests
    build:
      context: ./client/app
      dockerfile: Dockerfile.test

  weather-service:
    container_name: weather-service
    build:
      context: ./services/weather
      dockerfile: Dockerfile
    ports:
      - 6080:80
      - 6443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development