name: Eucre Game
on:
  push:
    paths:
      - 'docker-compose.yml'
      - 'services/eucre-game/*'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build eucre-game container
        run: docker-compose build eucre-game
