name: Library Service
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/library-service.yml"
      - "docker-compose.yml"
      - "services/common/**"
      - "services/library/**"
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build library-service container
        run: docker-compose build library-service
