name: Lobby Service
on:
  push:
    paths:
      - "docker-compose.yml"
      - "services/lobby-service/*"
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build lobby-service container
        run: docker-compose build lobby-service
