name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-web-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build web-app container
        run: docker-compose build web-app

  client-build-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build client-tests container
        run: docker-compose build client-tests
      - name: Run client-tests
        run: docker-compose run --rm client-tests

  server-build-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build weather-service container
        run: docker-compose build weather-service
