name: Docker Compose CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  client-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build client-tests container
        run: docker-compose build client-tests
      - name: Run client-tests
        run: docker-compose run --rm client-tests
