name: Weather Service
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/weather-service.yml"
      - "docker-compose.yml"
      - "services/weather/**"
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build weather-service container
        run: docker-compose build weather-service
